#!/usr/bin/env osascript

# symlink from /usr/local/bin

tell application "System Events"
    if not (exists application process "iTerm2") then
        tell application "iTerm"
            activate
        end tell
    else
        tell application "iTerm"
            create window with default profile
            activate
        end tell
    end if
end tell
